services:
    Kinoba\CouponBundle\CouponProvider:
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%kinoba_coupon.default_mask%'
            - '%kinoba_coupon.characters%'
            - '%kinoba_coupon.coupon_class%'
            - '%kinoba_coupon.generated_coupon_class%'

    Kinoba\CouponBundle\Form\CouponType:
        arguments:
            - '%kinoba_coupon.default_mask%'
